server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #GitHub 上面的git创库名字
          uri: git@github.com:MPL-git/springcloud-config2020.git
          #搜索目录
          search-paths:
            - springcloud-config2020
      #读取分支
      label: master

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
